# Generated by Django 5.0.3 on 2024-03-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='India',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('capital', models.CharField(max_length=20)),
                ('population', models.IntegerField()),
                ('famous_food', models.CharField(max_length=30)),
                ('popular_temples', models.CharField(max_length=40)),
                ('no_of_taluka', models.IntegerField()),
            ],
        ),
    ]
